// src/entrypoints/popup/App.tsx
import { createSignal, Match, onMount, Switch } from "solid-js";

import { getCurrentTab } from "@/common/browser";
import { detectConfig, type PlatformConfig } from "@/common/platforms";
import { theme } from "@/common/store/theme";

import SettingsButton from "./components/SettingsButton";
import Found from "./components/views/Found";
import Loading from "./components/views/Loading";
import Unsupported from "./components/views/Unsupported";

import 'virtual:uno.css';

const styles = {
  popup: "overflow-hidden rounded-xl",
  toolbar: "flex items-center justify-between py-3 px-4 bg-mantle border-b border-surface0",
  logo: "flex items-center gap-2 m-0",
};

type State =
  | { kind: "loading" }
  | { kind: "unsupported"; hostname?: string }
  | { kind: "found"; config: PlatformConfig };

export default function App() {
  const [state, setState] = createSignal<State>({ kind: "loading" });

  onMount(async () => {
    await theme.init();

    const tab = await getCurrentTab();
    if (!tab) {
      setState({ kind: "unsupported" });
      return;
    }

    const url = tab.url;
    const hostname = url?.startsWith("https://") ? new URL(url).hostname : "";
    const config = detectConfig(hostname);
    setState(config ? { kind: "found", config } : { kind: "unsupported", hostname });
  });

  return (
    <div class={styles.popup}>
      <header class={styles.toolbar}>
        <p class={styles.logo}>
          <span aria-hidden="true">⏭</span>
          <strong>BingeFlow</strong>
        </p>
        <SettingsButton />
      </header>

      <Switch>
        <Match when={state().kind === "loading"}>
          <Loading />
        </Match>
        <Match when={state().kind === "unsupported"}>
          <Unsupported hostname={(state() as { hostname?: string }).hostname} />
        </Match>
        <Match when={state().kind === "found"}>
          <Found config={(state() as { config: PlatformConfig }).config} />
        </Match>
      </Switch>
    </div>
  );
}

// src/popup/App.svelte
<script lang="ts">
import { onMount } from "svelte";
import { detectConfig, type PlatformConfig } from "../common/platforms";

import Found from "./states/Found.svelte";
import Loading from "./states/Loading.svelte";
import Unsupported from "./states/Unsupported.svelte";

type State =
	| { kind: "loading" }
	| { kind: "unsupported" }
	| { kind: "found"; config: PlatformConfig };

let state = $state<State>({ kind: "loading" });

onMount(async () => {
	const storedTheme = await chrome.storage.local.get("skip-intro.theme");
	const theme = storedTheme["skip-intro.theme"] === "latte" ? "latte" : "frappe";
	document.documentElement.setAttribute("data-theme", theme);

	const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
	const hostname = tab.url ? new URL(tab.url).hostname : "";
	const config = detectConfig(hostname);
	state = config ? { kind: "found", config } : { kind: "unsupported" };
});
</script>

<div class="popup">
	<header>
		<span class="icon">⏭</span>
		<span class="title">Skip Intro</span>
	</header>

	{#if state.kind === "loading"}
		<Loading />
	{:else if state.kind === "unsupported"}
		<Unsupported />
	{:else}
		<Found config={state.config} />
	{/if}
</div>

<style>
:global(*) {
	box-sizing: border-box;
	margin: 0;
	padding: 0;
}

:global(body) {
	background: var(--base);
	color: var(--text);
	width: 280px;
	transition: background-color 0.2s, color 0.2s;
}

.popup {
	background: var(--base);
	color: var(--text);
	width: 280px;
	overflow: hidden;
	border-radius: 12px;
}

header {
	display: flex;
	align-items: center;
	gap: 8px;
	padding: 16px 18px 14px;
	background: var(--mantle);
	border-bottom: 1px solid var(--surface0);
}

.icon {
	font-size: 18px;
	line-height: 1;
}

.title {
	font-size: 15px;
	font-weight: 600;
	letter-spacing: 0.01em;
	color: var(--text);
}
</style>
