// src/entrypoints/options/App.svelte
<script lang="ts">
import { onMount } from "svelte";
import Toast from "~/common/components/Toast.svelte";
import { saveSettings } from "~/common/settings";
import { theme } from "~/common/store/theme.svelte";
import Header from "./components/Header.svelte";
import KeyboardShortcuts from "./components/KeyboardShortcuts.svelte";
import LoadingState from "./components/LoadingState.svelte";
import VideoControls from "./components/VideoControls.svelte";
import { settings } from "./store/settings.svelte";

let saveStatus = $state<"idle" | "success" | "error">("idle");

onMount(async () => {
	await Promise.all([theme.init(), settings.init()]);
});

async function triggerSave() {
	if (!settings.current) return;

	try {
		await saveSettings($state.snapshot(settings.current));
		saveStatus = "success";
	} catch (error) {
		console.error("Failed to save settings:", error);
		saveStatus = "error";
	}

	setTimeout(() => {
		saveStatus = "idle";
	}, 2000);
}
</script>

{#if settings.current}
	<div class="container">
		<Header />

		<main class="main-content">
			<VideoControls
				bind:videoControls={settings.current.videoControls}
				onchange={triggerSave}
			/>
			<KeyboardShortcuts
				bind:videoControls={settings.current.videoControls}
				onchange={triggerSave}
			/>
		</main>
	</div>

	<Toast {saveStatus} />
{:else}
	<LoadingState />
{/if}

<style>
.container {
	width: 100%;
	display: flex;
	flex-direction: column;
	gap: var(--size-6);
}

.main-content {
	display: grid;
	grid-template-columns: 1fr;
	gap: var(--size-6);
	align-items: start;
}

@media (min-width: 768px) {
	.main-content {
		grid-template-columns: repeat(2, 1fr);
	}
}
</style>

// src/entrypoints/options/App.tsx
import { createSignal, onMount, Show } from "solid-js";

import Toast from "@/common/components/Toast";
import { saveSettings } from "@/common/settings";
import { theme } from "@/common/store/theme";
import type { VideoControlsConfig } from "@/common/video-controls";

import Header from "./components/Header";
import KeyboardShortcuts from "./components/KeyboardShortcuts";
import LoadingState from "./components/LoadingState";
import VideoControls from "./components/VideoControls";
import { settings } from "./store/settings";

import 'virtual:uno.css';

const styles = {
  container: "w-full flex flex-col gap-6",
  mainContent: "grid grid-cols-1 gap-6 items-start md:grid-cols-2",
};

export default function App() {
  const [saveStatus, setSaveStatus] = createSignal<"idle" | "success" | "error">("idle");

  onMount(async () => {
    await Promise.all([theme.init(), settings.init()]);
  });

  const triggerSave = async () => {
    if (!settings.current) return;

    try {
      const clone = JSON.parse(JSON.stringify(settings.current));
      await saveSettings(clone);
      setSaveStatus("success");
    } catch (error) {
      console.error("Failed to save settings:", error);
      setSaveStatus("error");
    }

    setTimeout(() => {
      setSaveStatus("idle");
    }, 2000);
  };

  const handleVideoControlsChange = (updater: (controls: VideoControlsConfig) => void) => {
    settings.update((s) => {
      updater(s.videoControls);
    });
    void triggerSave();
  };

  return (
    <Show when={settings.current} fallback={<LoadingState />}>
      {(s) => (
        <div class={styles.container}>
          <Header />

          <main class={styles.mainContent}>
            <VideoControls videoControls={s().videoControls} onchange={handleVideoControlsChange} />
            <KeyboardShortcuts
              videoControls={s().videoControls}
              onchange={handleVideoControlsChange}
            />
          </main>
          <Toast saveStatus={saveStatus()} />
        </div>
      )}
    </Show>
  );
}
