// src/entrypoints/popup/components/views/Found.tsx
import { For } from "solid-js";

import { getPlatformBehaviors, type PlatformConfig } from "@/common/platforms";

import BehaviorCard from "../BehaviorCard";

const styles = {
  found: "py-2",
  platform: "flex justify-between py-2 px-4 mb-1",
  platformLabel: "text-subtext0",
  platformValue: "m-0",
};

interface Props {
  config: PlatformConfig;
}

export default function Found(props: Props) {
  return (
    <section class={styles.found}>
      <dl class={styles.platform}>
        <dt class={styles.platformLabel}>Platform</dt>
        <dd class={styles.platformValue}>{props.config.label}</dd>
      </dl>

      <For each={getPlatformBehaviors(props.config)}>
        {(behavior) => <BehaviorCard behavior={behavior} />}
      </For>
    </section>
  );
}

// src/popup/states/Found.svelte
<script lang="ts">
import { getPlatformBehaviors, type PlatformConfig } from "../../common/platforms";
import BehaviorCard from "../components/BehaviorCard.svelte";

interface Props {
	config: PlatformConfig;
}

let { config }: Props = $props();
</script>

<div class="body">
	<div class="row platform-row">
		<span class="label">Platform</span>
		<span class="value">{config.label}</span>
	</div>

	{#each getPlatformBehaviors(config) as behavior (behavior.type)}
		<BehaviorCard {behavior} />
	{/each}
</div>

<style>
.body {
	padding: var(--size-2) 0;
}

.row {
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: var(--size-2) var(--size-4);
}

.platform-row {
	margin-bottom: var(--size-1);
}

.label {
	font-size: var(--font-size-00);
	font-weight: 600;
	color: var(--subtext0);
	text-transform: uppercase;
	letter-spacing: 0.08em;
}

.value {
	font-size: var(--font-size-0);
	font-weight: 600;
}
</style>
